"""
E6 — Drift anatomy on HAR (Disease B diagnostic).

Pre-registration: docs/E6_prereg.md (v2)

Asks whether HAR's adapter-resistant forgetting is carried by encoder drift inside
the readout-relevant subspace S, and whether that drift bears the fingerprint of
the encoder internally absorbing the input shift.

E4b's protocol LOGIC is reused; its MNIST geometry is not. S is the row space of
each dataset's own task-0 shared classifier, so rank(S) is 6 on HAR (six activity
classes) and 10 on MNIST. The random control is drawn at the matching rank and the
energy baseline recomputed per dataset (HAR 6/256 = 2.34%, MNIST 10/256 = 3.91%) —
per-dataset matching is what makes the two columns comparable at all.

Read order is fixed by the contract: M5 side-by-side, then H-B1, H-B2, H-B3', H-B4.

Usage:
    python scripts/drift_anatomy.py
    python scripts/drift_anatomy.py --skip-mnist      # HAR only
"""

import argparse
import json
import os
import sys
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn

sys.path.insert(0, str(Path(__file__).parent.parent))

from src.models.plcm import PLCM
from src.data.har_shift import HARShiftBenchmark
from src.data.permuted_mnist import PermutedMNISTBenchmark

SEEDS = [42, 1337, 2024]
N_EVAL = 2000
N_RANDOM = 20
RANDOM_SEED = 0

# Thresholds, fixed in the contract before any projection was computed.
H_B1_BAR = 0.43          # 2 x MNIST's measured ON/OFF drift_S ratio of 0.214
H_B2_BAR = 1.0           # in-S energy fraction >= 1.0x the S-energy share
H_B3_FACTOR = 2.0        # mean increment over {3,4} >= 2x mean over {1,2}
MNIST_REF_RATIO = 0.214

# HAR arms. OFF is generated by jobs_e6off (see prereg 0/0a: the audit found it
# absent, so its anatomy is computed on its OWN trajectories).
HAR_ARMS = {
    "v1-ON":      "runs/ckpt_e5_seed{s}/mafc_seed{s}",
    "OFF":        "runs/ckpt_e5_off_seed{s}/mafc_seed{s}",
    "v2-ON":      "runs/ckpt_e5d_v2on_seed{s}/mafc_seed{s}",
    "v2-control": "runs/ckpt_e5d_v2ctl_seed{s}/mafc_seed{s}",
}
# MNIST arms reuse E4b's mapping verbatim — ON seed 42 lives in fullrank_ref,
# NOT in an e4_on_seed42 directory (which does not exist).
MNIST_ARMS = {
    "ON": {42: "checkpoints/fullrank_ref/mafc_seed42",
           1337: "checkpoints/e4_on_seed1337/mafc_seed1337",
           2024: "checkpoints/e4_on_seed2024/mafc_seed2024"},
    "OFF": {s: f"checkpoints/e4_off_seed{s}/mafc_seed{s}" for s in SEEDS},
}


def load(d: str, task: int, epoch: int = 9) -> PLCM:
    p = Path(d) / f"task{task}_epoch{epoch}.pt"
    if not p.exists():
        raise FileNotFoundError(p)
    m = PLCM.load_from_checkpoint(
        torch.load(p, weights_only=True, map_location="cpu"))
    m.eval()
    for q in m.parameters():
        q.requires_grad = False
    return m


@torch.no_grad()
def encode(model: PLCM, x: torch.Tensor, use_adapter: bool, device, bs: int = 512):
    """Cell states as the encoder sees the input: post-adapter in ON, raw in OFF.

    Routes through model._apply_adapter rather than E4b's hardcoded flat reshape.
    HAR's adapter is per_step 9x9; the flat path would feed it 1152 dims.
    """
    out = []
    for i in range(0, x.shape[0], bs):
        xb = x[i:i + bs].to(device)
        if use_adapter and "0" in model.task_adapters:
            before = xb.shape
            xb = model._apply_adapter(xb, "0")
            assert xb.shape == before, (
                f"adapter changed input shape {before} -> {xb.shape}; "
                "adapter_mode is probably wrong for this dataset")
        _, (_, c) = model.lstm(xb)
        out.append(c[-1].cpu())
    return torch.cat(out)


def readout_projector(W: torch.Tensor) -> torch.Tensor:
    """P_S onto the row space of W. rank(S) = min(W.shape), per dataset."""
    _, _, Vt = torch.linalg.svd(W, full_matrices=False)
    return Vt.T @ Vt


def random_projector(dim: int, rank: int, gen: torch.Generator) -> torch.Tensor:
    Q, _ = torch.linalg.qr(torch.randn(dim, rank, generator=gen))
    return Q @ Q.T


def drift_in(P, f0, f1) -> float:
    return float(1.0 - nn.functional.cosine_similarity(f0 @ P, f1 @ P, dim=1).mean())


def principal_angle(W0: torch.Tensor, W1: torch.Tensor) -> float:
    """Largest principal angle (degrees) between two row spaces — M4's control."""
    def basis(W):
        _, _, Vt = torch.linalg.svd(W, full_matrices=False)
        return Vt.T
    s = torch.linalg.svdvals(basis(W0).T @ basis(W1)).clamp(-1, 1)
    return float(torch.rad2deg(torch.arccos(s.min())))


def anatomy(dirs: dict, use_adapter: bool, x, device, per_task: bool):
    """M1/M2 (+M3 increments, +M4 angle) for one arm across seeds."""
    rows = []
    for seed in SEEDS:
        d = dirs[seed] if isinstance(dirs, dict) else dirs.format(s=seed)
        m0, m4 = load(d, 0), load(d, 4)
        f0, f4 = encode(m0, x, use_adapter, device), encode(m4, x, use_adapter, device)

        W0 = m0.classifier.weight.detach()
        rank = min(W0.shape)
        P_S = readout_projector(W0)
        dim = f0.shape[1]

        gen = torch.Generator().manual_seed(RANDOM_SEED + seed)
        rand = [drift_in(random_projector(dim, rank, gen), f0, f4)
                for _ in range(N_RANDOM)]

        delta = f4 - f0
        energy_frac = float((delta @ P_S).pow(2).sum() / delta.pow(2).sum())
        rep_share = float((f0 @ P_S).pow(2).sum() / f0.pow(2).sum())

        # M4: does the verdict survive defining S from theta_4's classifier?
        P_S4 = readout_projector(m4.classifier.weight.detach())
        rec = {
            "seed": seed, "rank": rank,
            "drift_full": float(1.0 - nn.functional.cosine_similarity(f0, f4, dim=1).mean()),
            "drift_S": drift_in(P_S, f0, f4),
            "drift_S_theta4": drift_in(P_S4, f0, f4),
            "drift_random": float(np.mean(rand)),
            "energy_frac": energy_frac,
            "rep_share": rep_share,
            "aim": energy_frac / rep_share if rep_share else float("nan"),
            "angle_S0_S4": principal_angle(W0, m4.classifier.weight.detach()),
            "random_baseline": rank / dim,
        }

        if per_task:   # M3 — increments across consecutive task boundaries
            inc = []
            prev = f0
            for k in range(1, 5):
                fk = encode(load(d, k), x, use_adapter, device)
                inc.append(drift_in(P_S, prev, fk))
                prev = fk
            rec["increments"] = inc
        rows.append(rec)
    return rows


def agg(rows, key):
    v = [r[key] for r in rows]
    return float(np.mean(v)), float(np.std(v))


def main():
    ap = argparse.ArgumentParser(description="E6 drift anatomy")
    ap.add_argument("--out", default="runs/e6/")
    ap.add_argument("--device", default="cpu")
    ap.add_argument("--skip-mnist", action="store_true")
    args = ap.parse_args()
    device = torch.device(args.device)
    os.makedirs(args.out, exist_ok=True)

    har = HARShiftBenchmark(num_tasks=5, root=".", batch_size=256)
    _, te = har.get_task_loaders(0)
    xh = torch.cat([xb for xb, _ in te])[:N_EVAL]

    results, missing = {}, []
    for arm, tmpl in HAR_ARMS.items():
        try:
            results[("HAR", arm)] = anatomy(
                tmpl, use_adapter=("ON" in arm or "control" in arm),
                x=xh, device=device, per_task=(arm == "OFF"))
        except FileNotFoundError as e:
            missing.append(f"HAR/{arm}: {e}")

    if not args.skip_mnist:
        mb = PermutedMNISTBenchmark(num_tasks=5, batch_size=256, seed=42)
        _, mte = mb.get_task_loaders(0)
        xm = torch.cat([xb for xb, _ in mte])[:N_EVAL]
        for arm, dirs in MNIST_ARMS.items():
            try:
                results[("MNIST", arm)] = anatomy(
                    dirs, use_adapter=(arm == "ON"), x=xm, device=device,
                    per_task=False)
            except FileNotFoundError as e:
                missing.append(f"MNIST/{arm}: {e}")

    # ---- M5 FIRST, per the contract's read order --------------------------
    print("=" * 82)
    print("M5 — TWO-DATASET ANATOMY (read before any hypothesis)")
    print("=" * 82)
    print(f"  {'dataset/arm':<20}{'rank':>5}{'drift_full':>12}{'drift_S':>10}"
          f"{'drift_rand':>12}{'energy':>9}{'S-share':>9}{'aim':>7}")
    for (ds, arm), rows in results.items():
        r = lambda k: agg(rows, k)[0]
        print(f"  {ds+'/'+arm:<20}{rows[0]['rank']:>5}{r('drift_full'):>12.4f}"
              f"{r('drift_S'):>10.4f}{r('drift_random'):>12.4f}"
              f"{r('energy_frac')*100:>8.2f}%{r('rep_share')*100:>8.2f}%{r('aim'):>7.2f}")
    if missing:
        print("\n  ABSENT (reported, not substituted):")
        for m in missing:
            print(f"    {m}")

    def ratio(ds, on_key):
        if (ds, on_key) not in results or (ds, "OFF") not in results:
            return None
        return agg(results[(ds, on_key)], "drift_S")[0] / agg(results[(ds, "OFF")], "drift_S")[0]

    print("\n" + "=" * 82)
    print("HYPOTHESES")
    print("=" * 82)
    har_ratio = ratio("HAR", "v1-ON")
    mn_ratio = ratio("MNIST", "ON")
    if mn_ratio is not None:
        print(f"  MNIST ON/OFF drift_S ratio (instrument check): {mn_ratio:.3f}"
              f"   [E4b measured 0.214]")
    if har_ratio is None:
        print("  H-B1  UNMEASURABLE — OFF arm checkpoints absent")
    else:
        print(f"  H-B1  HAR ON/OFF drift_S ratio {har_ratio:.3f} >= {H_B1_BAR}"
              f"  -> {'PASS' if har_ratio >= H_B1_BAR else 'FAIL'}")

    h2 = None
    if ("HAR", "v1-ON") in results:
        h2 = agg(results[("HAR", "v1-ON")], "aim")[0]
        print(f"  H-B2  HAR ON in-S energy {h2:.3f}x its S-share >= {H_B2_BAR}"
              f"  -> {'PASS' if h2 >= H_B2_BAR else 'FAIL'}   [MNIST ON was 0.44x]")

    h3 = None
    if ("HAR", "OFF") in results and "increments" in results[("HAR", "OFF")][0]:
        inc = np.array([r["increments"] for r in results[("HAR", "OFF")]])
        m_lo, m_hi = inc[:, :2].mean(), inc[:, 2:].mean()
        h3 = m_hi / m_lo if m_lo else float("inf")
        print(f"\n  M3 per-task in-S increments (OFF): "
              f"{[round(v,4) for v in inc.mean(0)]}")
        print(f"  H-B3' mean{{3,4}}={m_hi:.4f} vs {H_B3_FACTOR}x mean{{1,2}}={H_B3_FACTOR*m_lo:.4f}"
              f"  -> {'PASS' if h3 >= H_B3_FACTOR else 'FAIL'}  (ratio {h3:.2f}x)")
        dmg = [0.0098, 0.0655, 0.688, 0.643]
        from scipy.stats import spearmanr
        rho = spearmanr(inc.mean(0), dmg).statistic
        print(f"  (descriptive only) Spearman rho vs row-0 damage = {rho:.3f}")

    h4 = None
    if ("HAR", "v1-ON") in results and ("HAR", "OFF") in results:
        ang = agg(results[("HAR", "v1-ON")], "angle_S0_S4")[0]
        alt = (agg(results[("HAR", "v1-ON")], "drift_S_theta4")[0]
               / agg(results[("HAR", "OFF")], "drift_S_theta4")[0])
        same = (har_ratio >= H_B1_BAR) == (alt >= H_B1_BAR)
        h4 = same
        print(f"\n  H-B4  principal angle S(theta0) vs S(theta4) = {ang:.1f} deg;"
              f" ratio under theta4-S = {alt:.3f}")
        print(f"        verdict unchanged -> {'PASS' if same else 'FAIL — co-adaptation is a live channel'}")

    if har_ratio is not None and h2 is not None and h3 is not None:
        if har_ratio >= H_B1_BAR and h2 >= H_B2_BAR and h3 >= H_B3_FACTOR:
            br = "(A) Disease B confirmed as internal shift absorption -> draft E7"
        elif har_ratio >= H_B1_BAR and h2 >= H_B2_BAR:
            br = "(B) in-S drift real and dominant but NOT tracked to shift severity -> cure PAUSED"
        elif har_ratio >= H_B1_BAR:
            br = "(C) elevated in-S but not dominant -> size both parts"
        else:
            br = "(D) drift as steered as MNIST -> in-S hypothesis WRONG, back to diagnosis"
        print(f"\n  BRANCH: {br}")

    out = {f"{d}/{a}": rows for (d, a), rows in results.items()}
    json.dump({"arms": out, "missing": missing,
               "h_b1_ratio": har_ratio, "h_b2_aim": h2, "h_b3_ratio": h3,
               "h_b4_verdict_stable": h4},
              open(os.path.join(args.out, "anatomy.json"), "w"), indent=2, default=float)
    print(f"\n  wrote {args.out}anatomy.json")


if __name__ == "__main__":
    main()
